language: minimal
dist: xenial

addons:
  apt:
    packages:
      - lua-check

beforescript: luacheck .

script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
